import type { Employee, Team, Alert, ChartPoint } from "@/types/kiple";

export const mockEmployees: Employee[] = [
  {
    id: 1,
    name: "João Silva",
    position: "Desenvolvedor Sênior",
    department: "Tecnologia",
    team: "Squad Alpha",
    tenure: 24,
    engagementScore: 92,
    turnoverRisk: "low",
    performance: "star",
    turnoverCost: 0,
    email: "joao.silva@empresa.com",
    joinDate: "2022-03-15",
    lastSurvey: "2024-01-10",
    careerProgress: 78,
    skillsScore: 88,
  },
  {
    id: 2,
    name: "Maria Santos",
    position: "HR Manager",
    department: "RH",
    team: "People & Culture",
    tenure: 36,
    engagementScore: 88,
    turnoverRisk: "medium",
    performance: "high",
    turnoverCost: 45000,
    email: "maria.santos@empresa.com",
    joinDate: "2021-01-20",
    lastSurvey: "2024-01-08",
    careerProgress: 65,
    skillsScore: 82,
  },
  {
    id: 3,
    name: "Carlos Mendes",
    position: "Analista de Dados",
    department: "Tecnologia",
    team: "Data & Analytics",
    tenure: 8,
    engagementScore: 61,
    turnoverRisk: "high",
    performance: "medium",
    turnoverCost: 32000,
    email: "carlos.mendes@empresa.com",
    joinDate: "2023-05-10",
    lastSurvey: "2024-01-05",
    careerProgress: 32,
    skillsScore: 64,
  },
  {
    id: 4,
    name: "Ana Oliveira",
    position: "Product Designer",
    department: "Produto",
    team: "Design System",
    tenure: 18,
    engagementScore: 95,
    turnoverRisk: "low",
    performance: "star",
    turnoverCost: 0,
    email: "ana.oliveira@empresa.com",
    joinDate: "2022-07-01",
    lastSurvey: "2024-01-11",
    careerProgress: 82,
    skillsScore: 91,
  },
  {
    id: 5,
    name: "Rafael Costa",
    position: "Gerente de Vendas",
    department: "Comercial",
    team: "Sales Enterprise",
    tenure: 14,
    engagementScore: 74,
    turnoverRisk: "medium",
    performance: "high",
    turnoverCost: 28000,
    email: "rafael.costa@empresa.com",
    joinDate: "2022-11-15",
    lastSurvey: "2024-01-07",
    careerProgress: 55,
    skillsScore: 72,
  },
  {
    id: 6,
    name: "Fernanda Lima",
    position: "Engenheira de Software",
    department: "Tecnologia",
    team: "Squad Beta",
    tenure: 6,
    engagementScore: 55,
    turnoverRisk: "high",
    performance: "medium",
    turnoverCost: 38000,
    email: "fernanda.lima@empresa.com",
    joinDate: "2023-07-20",
    lastSurvey: "2023-12-28",
    careerProgress: 28,
    skillsScore: 59,
  },
  {
    id: 7,
    name: "Lucas Rocha",
    position: "Analista Financeiro",
    department: "Financeiro",
    team: "Finance",
    tenure: 48,
    engagementScore: 82,
    turnoverRisk: "low",
    performance: "high",
    turnoverCost: 0,
    email: "lucas.rocha@empresa.com",
    joinDate: "2020-02-10",
    lastSurvey: "2024-01-09",
    careerProgress: 70,
    skillsScore: 79,
  },
  {
    id: 8,
    name: "Patricia Souza",
    position: "Marketing Lead",
    department: "Marketing",
    team: "Growth",
    tenure: 22,
    engagementScore: 90,
    turnoverRisk: "low",
    performance: "star",
    turnoverCost: 0,
    email: "patricia.souza@empresa.com",
    joinDate: "2022-04-05",
    lastSurvey: "2024-01-10",
    careerProgress: 75,
    skillsScore: 85,
  },
];

export const mockTeams: Team[] = [
  { id: 1, name: "Squad Alpha", department: "Tecnologia", lead: "João Silva", size: 8, engagementAvg: 89, turnoverRate: 8.5, performance: "star", atRiskCount: 0 },
  { id: 2, name: "Data & Analytics", department: "Tecnologia", lead: "Carlos Mendes", size: 5, engagementAvg: 62, turnoverRate: 24.0, performance: "medium", atRiskCount: 2 },
  { id: 3, name: "Design System", department: "Produto", lead: "Ana Oliveira", size: 6, engagementAvg: 93, turnoverRate: 4.2, performance: "star", atRiskCount: 0 },
  { id: 4, name: "Sales Enterprise", department: "Comercial", lead: "Rafael Costa", size: 12, engagementAvg: 76, turnoverRate: 15.3, performance: "high", atRiskCount: 1 },
  { id: 5, name: "People & Culture", department: "RH", lead: "Maria Santos", size: 4, engagementAvg: 84, turnoverRate: 10.0, performance: "high", atRiskCount: 0 },
  { id: 6, name: "Finance", department: "Financeiro", lead: "Lucas Rocha", size: 7, engagementAvg: 80, turnoverRate: 7.5, performance: "high", atRiskCount: 0 },
  { id: 7, name: "Growth", department: "Marketing", lead: "Patricia Souza", size: 9, engagementAvg: 88, turnoverRate: 6.8, performance: "star", atRiskCount: 0 },
  { id: 8, name: "Squad Beta", department: "Tecnologia", lead: "Fernanda Lima", size: 7, engagementAvg: 58, turnoverRate: 28.6, performance: "low", atRiskCount: 3 },
];

export const engagementTrend: ChartPoint[] = [
  { month: "Ago", value: 78, secondary: 72 },
  { month: "Set", value: 81, secondary: 74 },
  { month: "Out", value: 79, secondary: 71 },
  { month: "Nov", value: 84, secondary: 76 },
  { month: "Dez", value: 88, secondary: 80 },
  { month: "Jan", value: 91, secondary: 83 },
];

export const turnoverTrend: ChartPoint[] = [
  { month: "Ago", value: 16.2 },
  { month: "Set", value: 15.8 },
  { month: "Out", value: 14.5 },
  { month: "Nov", value: 13.9 },
  { month: "Dez", value: 13.2 },
  { month: "Jan", value: 12.8 },
];

export const departmentEngagement = [
  { name: "Tecnologia", value: 76, color: "#2563EB" },
  { name: "Produto", value: 93, color: "#10B981" },
  { name: "Comercial", value: 76, color: "#F59E0B" },
  { name: "RH", value: 84, color: "#8B5CF6" },
  { name: "Marketing", value: 88, color: "#EC4899" },
  { name: "Financeiro", value: 80, color: "#06B6D4" },
];

export const performanceDistribution = [
  { name: "Estrelas", value: 3, color: "#2563EB" },
  { name: "Alto", value: 3, color: "#10B981" },
  { name: "Médio", value: 2, color: "#F59E0B" },
  { name: "Baixo", value: 0, color: "#EF4444" },
];

export const mockAlerts: Alert[] = [
  { id: "1", type: "danger", title: "3 funcionários em alto risco", message: "Carlos Mendes, Fernanda Lima e mais 1 apresentam sinais de turnover iminente.", timestamp: "há 2h", read: false },
  { id: "2", type: "warning", title: "Squad Beta com engajamento crítico", message: "O engajamento do Squad Beta caiu 8 pontos no último mês (58%).", timestamp: "há 5h", read: false },
  { id: "3", type: "info", title: "Pesquisa de engajamento em aberto", message: "47 funcionários ainda não responderam à pesquisa de Janeiro.", timestamp: "há 1d", read: true },
  { id: "4", type: "success", title: "Meta de turnover superada", message: "O departamento de Produto atingiu taxa de turnover de 4.2% (meta: 8%).", timestamp: "há 2d", read: true },
];
